apiVersion: v1
kind: Service
metadata:
  labels:
    app: localregistry
    app.kubernetes.io/managed-by: Helm
  name: localregistry
spec:
  clusterIP: {{ .Values.localregistry.clusterIP | quote}}
  clusterIPs:
  - {{ .Values.localregistry.clusterIP }}
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: localregistry
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}