apiVersion: v1
kind: Service
metadata:
  labels:
    app: webserver
    app.kubernetes.io/managed-by: Helm
  name: webserver
spec:
  clusterIP: {{ .Values.webserver.clusterIP | quote}}
  clusterIPs:
  - {{ .Values.webserver.clusterIP }}
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: {{ .Values.webserver.name }}
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}